ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --resultlog=resultlog.log
  inifile: None
  rootdir: /app

Command exited with non-zero status 4
	Command being timed: "pytest -vvv test_app.py --resultlog=resultlog.log"
	User time (seconds): 0.12
	System time (seconds): 0.01
	Percent of CPU this job got: 96%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.15
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 24484
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 5016
	Voluntary context switches: 0
	Involuntary context switches: 7
	Swaps: 0
	File system inputs: 0
	File system outputs: 688
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 4
